### ISSUE TITLE
fluid type tool tip

### ISSUE THREAD

**Issue by Dragonracer73** [TheRoBrit/Moo-Fluids#49] opened 2017-03-25 18:04 UTC
This is a cool mod, can you possibly add support, tool tip wise for waila, hwyla, and the one probe? It would be nice to know what type of cow we're looking at. Thanx

**Comment by TheRoBrit** [comment] 2017-03-25 21:31
Duplicate of #45. Closing.

**Closed by TheRoBrit** 2017-03-25 21:31 UTC
