### ISSUE TITLE
The One Prob Support

### ISSUE THREAD

**Issue by twizcraft** [TheRoBrit/Moo-Fluids#47] opened 2017-03-22 00:23 UTC
Can we get support for The one Probe so it will show what type of fluid the cows are in 1.10.2 please and thanks

**Comment by Jo-Mamma75** [comment] 2017-03-25 08:02
And as an alternative or addition to would it be possible to add support to Hwyla (the successor of Waila) to show the type of cow and cool-down period for the 1.10.2 version of the mod?

**Comment by TheRoBrit** [comment] 2017-03-25 21:32
Duplicate of #45. Closing.

**Closed by TheRoBrit** 2017-03-25 21:32 UTC
